version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11.9
    commands:
      - echo "Installing AWS CLI and SAM CLI"
      - pip install --upgrade awscli aws-sam-cli

  pre_build:
    commands:
      - echo "Retrieving OpenAI API key from Parameter Store"
      - export OPENAI_API_KEY=$(aws ssm get-parameter --name "/fantasy-ai/openai_api_key" --with-decryption --query "Parameter.Value" --output text)
      - echo "OPENAI_API_KEY successfully retrieved"

  build:
    commands:
      - echo "Building and packaging SAM application"
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml